import { User } from './users';

export const USERS: User[] = [
  {
    id: 1,
    name: 'Leanne Graham',
    surname: 'Bret',
    birthDate: new Date(1992, 3, 15),
    citizenship: 'USA',
    photo: 'assets/images/users/1.jpg',
    email: 'bret@gmail.com',
    facebook: '@LeaneGraham',
    twitter: '@LeaneGraham',
    instagram: '@LeaneGraham',
    role: 'Actor',
  },
  {
    id: 2,
    name: 'Hugh',
    surname: 'Jackman',
    birthDate: new Date(1967, 3, 12),
    citizenship: 'USA',
    photo: 'assets/images/users/1.jpg',
    email: 'hugh@jackman.xman',
    facebook: '@HughJackman',
    twitter: '@HughJackman',
    instagram: '@HughJackman',
    role: 'Actor',
  },
  {
    id: 3,
    name: 'Johny',
    surname: 'Deep',
    birthDate: new Date(1968, 3, 12),
    citizenship: 'USA',
    photo: 'assets/images/users/1.jpg',
    email: 'johny@deep.',
    facebook: '@HughJackman',
    twitter: '@HughJackman',
    instagram: '@HughJackman',
    role: 'Actor',
  },
];
